# Generated by Django 4.0.4 on 2022-05-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('regno', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.cname')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit1', models.CharField(blank=True, choices=[('BICT 412', 'BICT 412'), ('STAT 121', 'STAT 121'), ('COMP 202', 'COMP 202')], max_length=30)),
                ('unit2', models.CharField(blank=True, choices=[('BICT 412', 'BICT 412'), ('STAT 121', 'STAT 121'), ('COMP 202', 'COMP 202')], max_length=30)),
                ('unit3', models.CharField(blank=True, choices=[('BICT 412', 'BICT 412'), ('STAT 121', 'STAT 121'), ('COMP 202', 'COMP 202')], max_length=30)),
                ('unit4', models.CharField(blank=True, choices=[('BICT 412', 'BICT 412'), ('STAT 121', 'STAT 121'), ('COMP 202', 'COMP 202')], max_length=30)),
                ('unit5', models.CharField(blank=True, choices=[('BICT 412', 'BICT 412'), ('STAT 121', 'STAT 121'), ('COMP 202', 'COMP 202')], max_length=30)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('school', models.CharField(choices=[('SSAT', 'SSAT'), ('Education', 'Education'), ('HDS', 'HDS'), ('MED', 'MED')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.BooleanField(default=False, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='myreg@gmail.com', max_length=254)),
                ('f_name', models.CharField(default='F_NAME', max_length=30)),
                ('l_name', models.CharField(default='M_NAME', max_length=30)),
                ('surname', models.CharField(default='SURNAME', max_length=30)),
                ('pic', models.ImageField(default='E:\\IPweb\\media\\profile_pics\\TT.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
